cd ../../../
echo removing abi
rm -rf abi
echo removing android
rm -rf android
echo removing art
rm -rf art
echo removing bionic
rm -rf bionic
echo removing bootable
rm -rf bootable
echo removing build
rm -rf build
echo removing cts
rm -rf cts
echo removing dalvik
rm -rf dalvik
echo removing developers
rm -rf developers
echo removing development
rm -rf development
echo removing docs
rm -rf docs
echo removing external
rm -rf external
echo removing frameworks
rm -rf frameworks
echo removing hardware
rm -rf hardware
echo removing libcore
rm -rf libcore
echo removing libnativehelper
rm -rf libnativehelper
echo removing ndk
rm -rf ndk
echo removing out
rm -rf out
echo removing packages
rm -rf packages
echo removing pdk
rm -rf pdk
echo removing prebuilt
rm -rf prebuilt
echo removing prebuilts
rm -rf prebuilts
echo removing sdk
rm -rf sdk
echo removing system
rm -rf system
echo removing tools
rm -rf tools
echo removing vendor/cm
rm -rf vendor/cm
echo removing vendor/cyngn
rm -rf vendor/cyngn
echo removing Makefile
chmod 0755 Makefile
rm Makefile


