#
# Audio Package 10 - Mako
# 
# Include this file in a product makefile to include these audio files
#
# 

LOCAL_PATH:= frameworks/base/data/sounds

LOCAL_PATH:= frameworks/base/data/sounds

# Alarms
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/alarms/ogg/Alarm01.ogg:system/media/audio/alarms/Alarm01.ogg \
    $(LOCAL_PATH)/alarms/ogg/Alarm02.ogg:system/media/audio/alarms/Alarm02.ogg \
    $(LOCAL_PATH)/alarms/ogg/Alarm03.ogg:system/media/audio/alarms/Alarm03.ogg \
    $(LOCAL_PATH)/alarms/ogg/Argon.ogg:system/media/audio/alarms/Argon.ogg \
    $(LOCAL_PATH)/alarms/ogg/Barium.ogg:system/media/audio/alarms/Barium.ogg \
    $(LOCAL_PATH)/alarms/ogg/BeepBeepAlarm.ogg:system/media/audio/alarms/BeepBeepAlarm.ogg \
    $(LOCAL_PATH)/alarms/ogg/BuzzerAlarm.ogg:system/media/audio/alarms/BuzzerAlarm.ogg \
    $(LOCAL_PATH)/alarms/ogg/Carbon.ogg:system/media/audio/alarms/Carbon.ogg \
    $(LOCAL_PATH)/alarms/ogg/Cesium.ogg:system/media/audio/alarms/Cesium.ogg \
    $(LOCAL_PATH)/alarms/ogg/Copernicium.ogg:system/media/audio/alarms/Copernicium.ogg \
    $(LOCAL_PATH)/alarms/ogg/Cricket.ogg:system/media/audio/alarms/Cricket.ogg \
    $(LOCAL_PATH)/alarms/ogg/Curium.ogg:system/media/audio/alarms/Curium.ogg \
    $(LOCAL_PATH)/alarms/ogg/CyanAlarm.ogg:system/media/audio/alarms/CyanAlarm.ogg \
    $(LOCAL_PATH)/alarms/ogg/DayBreak.ogg:system/media/audio/alarms/DayBreak.ogg \
    $(LOCAL_PATH)/alarms/ogg/Dingdong.ogg:system/media/audio/alarms/Dingdong.ogg \
    $(LOCAL_PATH)/alarms/ogg/Fermium.ogg:system/media/audio/alarms/Fermium.ogg \
    $(LOCAL_PATH)/alarms/ogg/Hassium.ogg:system/media/audio/alarms/Hassium.ogg \
    $(LOCAL_PATH)/alarms/ogg/Helium.ogg:system/media/audio/alarms/Helium.ogg \
    $(LOCAL_PATH)/alarms/ogg/Krypton.ogg:system/media/audio/alarms/Krypton.ogg \
    $(LOCAL_PATH)/alarms/ogg/Neon.ogg:system/media/audio/alarms/Neon.ogg \
    $(LOCAL_PATH)/alarms/ogg/Neptunium.ogg:system/media/audio/alarms/Neptunium.ogg \
    $(LOCAL_PATH)/alarms/ogg/Nimble.ogg:system/media/audio/alarms/Nimble.ogg \
    $(LOCAL_PATH)/alarms/ogg/Nobelium.ogg:system/media/audio/alarms/Nobelium.ogg \
    $(LOCAL_PATH)/alarms/ogg/Osmium.ogg:system/media/audio/alarms/Osmium.ogg \
    $(LOCAL_PATH)/alarms/ogg/Oxygen.ogg:system/media/audio/alarms/Oxygen.ogg \
    $(LOCAL_PATH)/alarms/ogg/PiezoAlarm.ogg:system/media/audio/alarms/PiezoAlarm.ogg \
    $(LOCAL_PATH)/alarms/ogg/Platinum.ogg:system/media/audio/alarms/Platinum.ogg \
    $(LOCAL_PATH)/alarms/ogg/Plutonium.ogg:system/media/audio/alarms/Plutonium.ogg \
    $(LOCAL_PATH)/alarms/ogg/Promethium.ogg:system/media/audio/alarms/Promethium.ogg \
    $(LOCAL_PATH)/alarms/ogg/RingingAlarm.ogg:system/media/audio/alarms/RingingAlarm.ogg \
    $(LOCAL_PATH)/alarms/ogg/RoosterAlarm.ogg:system/media/audio/alarms/RoosterAlarm.ogg \
    $(LOCAL_PATH)/alarms/ogg/Scandium.ogg:system/media/audio/alarms/Scandium.ogg \
    $(LOCAL_PATH)/alarms/ogg/WakeUp.ogg:system/media/audio/alarms/WakeUp.ogg

# Notifications
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/notifications/ogg/Adara.ogg:system/media/audio/notifications/Adara.ogg \
    $(LOCAL_PATH)/notifications/ogg/Alarm_Classic.ogg:system/media/audio/notifications/Alarm_Classic.ogg \
    $(LOCAL_PATH)/notifications/ogg/Aldebaran.ogg:system/media/audio/notifications/Aldebaran.ogg \
    $(LOCAL_PATH)/notifications/ogg/Altair.ogg:system/media/audio/notifications/Altair.ogg \
    $(LOCAL_PATH)/notifications/ogg/Alya.ogg:system/media/audio/notifications/Alya.ogg \
    $(LOCAL_PATH)/notifications/ogg/Antares.ogg:system/media/audio/notifications/Antares.ogg \
    $(LOCAL_PATH)/notifications/ogg/Antimony.ogg:system/media/audio/notifications/Antimony.ogg \
    $(LOCAL_PATH)/notifications/ogg/Arcturus.ogg:system/media/audio/notifications/Arcturus.ogg \
    $(LOCAL_PATH)/notifications/ogg/Argon.ogg:system/media/audio/notifications/Argon.ogg \
    $(LOCAL_PATH)/notifications/ogg/Beat_Box_Android.ogg:system/media/audio/notifications/Beat_Box_Android.ogg \
    $(LOCAL_PATH)/notifications/ogg/Bellatrix.ogg:system/media/audio/notifications/Bellatrix.ogg \
    $(LOCAL_PATH)/notifications/ogg/Beryllium.ogg:system/media/audio/notifications/Beryllium.ogg \
    $(LOCAL_PATH)/notifications/ogg/Betelgeuse.ogg:system/media/audio/notifications/Betelgeuse.ogg \
    $(LOCAL_PATH)/notifications/ogg/CaffeineSnake.ogg:system/media/audio/notifications/CaffeineSnake.ogg \
    $(LOCAL_PATH)/notifications/ogg/Canopus.ogg:system/media/audio/notifications/Canopus.ogg \
    $(LOCAL_PATH)/notifications/ogg/Capella.ogg:system/media/audio/notifications/Capella.ogg \
    $(LOCAL_PATH)/notifications/ogg/CarLock.ogg:system/media/audio/notifications/CarLock.ogg \
    $(LOCAL_PATH)/notifications/ogg/Castor.ogg:system/media/audio/notifications/Castor.ogg \
    $(LOCAL_PATH)/notifications/ogg/CetiAlpha.ogg:system/media/audio/notifications/CetiAlpha.ogg \
    $(LOCAL_PATH)/notifications/ogg/Cobalt.ogg:system/media/audio/notifications/Cobalt.ogg \
    $(LOCAL_PATH)/notifications/ogg/Cricket.ogg:system/media/audio/notifications/Cricket.ogg \
    $(LOCAL_PATH)/notifications/ogg/CyanMail.ogg:system/media/audio/notifications/CyanMail.ogg \
    $(LOCAL_PATH)/notifications/ogg/CyanMessage.ogg:system/media/audio/notifications/CyanMessage.ogg \
    $(LOCAL_PATH)/notifications/ogg/CyanPing.ogg:system/media/audio/notifications/CyanPing.ogg \
    $(LOCAL_PATH)/notifications/ogg/DearDeer.ogg:system/media/audio/notifications/DearDeer.ogg \
    $(LOCAL_PATH)/notifications/ogg/Deneb.ogg:system/media/audio/notifications/Deneb.ogg \
    $(LOCAL_PATH)/notifications/ogg/Doink.ogg:system/media/audio/notifications/Doink.ogg \
    $(LOCAL_PATH)/notifications/ogg/DontPanic.ogg:system/media/audio/notifications/DontPanic.ogg \
    $(LOCAL_PATH)/notifications/ogg/Drip.ogg:system/media/audio/notifications/Drip.ogg \
    $(LOCAL_PATH)/notifications/ogg/Electra.ogg:system/media/audio/notifications/Electra.ogg \
    $(LOCAL_PATH)/notifications/ogg/F1_MissedCall.ogg:system/media/audio/notifications/F1_MissedCall.ogg \
    $(LOCAL_PATH)/notifications/ogg/F1_New_MMS.ogg:system/media/audio/notifications/F1_New_MMS.ogg \
    $(LOCAL_PATH)/notifications/ogg/F1_New_SMS.ogg:system/media/audio/notifications/F1_New_SMS.ogg \
    $(LOCAL_PATH)/notifications/ogg/facebook_ringtone_pop.m4a:system/media/audio/notifications/facebook_ringtone_pop.m4a \
    $(LOCAL_PATH)/notifications/ogg/Fluorine.ogg:system/media/audio/notifications/Fluorine.ogg \
    $(LOCAL_PATH)/notifications/ogg/Fomalhaut.ogg:system/media/audio/notifications/Fomalhaut.ogg \
    $(LOCAL_PATH)/notifications/ogg/Gallium.ogg:system/media/audio/notifications/Gallium.ogg \
    $(LOCAL_PATH)/notifications/ogg/hangout_dingtone.m4a:system/media/audio/notifications/hangout_dingtone.m4a \
    $(LOCAL_PATH)/notifications/ogg/Heaven.ogg:system/media/audio/notifications/Heaven.ogg \
    $(LOCAL_PATH)/notifications/ogg/Helium.ogg:system/media/audio/notifications/Helium.ogg \
    $(LOCAL_PATH)/notifications/ogg/Highwire.ogg:system/media/audio/notifications/Highwire.ogg \
    $(LOCAL_PATH)/notifications/ogg/Hojus.ogg:system/media/audio/notifications/Hojus.ogg \
    $(LOCAL_PATH)/notifications/ogg/Iridium.ogg:system/media/audio/notifications/Iridium.ogg \
    $(LOCAL_PATH)/notifications/ogg/Krypton.ogg:system/media/audio/notifications/Krypton.ogg \
    $(LOCAL_PATH)/notifications/ogg/KzurbSonar.ogg:system/media/audio/notifications/KzurbSonar.ogg \
    $(LOCAL_PATH)/notifications/ogg/Lalande.ogg:system/media/audio/notifications/Lalande.ogg \
    $(LOCAL_PATH)/notifications/ogg/Merope.ogg:system/media/audio/notifications/Merope.ogg \
    $(LOCAL_PATH)/notifications/ogg/Mira.ogg:system/media/audio/notifications/Mira.ogg \
    $(LOCAL_PATH)/notifications/ogg/moonbeam.ogg:system/media/audio/notifications/moonbeam.ogg \
    $(LOCAL_PATH)/notifications/ogg/Naughty.ogg:system/media/audio/notifications/Naughty.ogg \
    $(LOCAL_PATH)/notifications/ogg/OnTheHunt.ogg:system/media/audio/notifications/OnTheHunt.ogg \
    $(LOCAL_PATH)/notifications/ogg/Palladium.ogg:system/media/audio/notifications/Palladium.ogg \
    $(LOCAL_PATH)/notifications/ogg/pixiedust.ogg:system/media/audio/notifications/pixiedust.ogg \
    $(LOCAL_PATH)/notifications/ogg/pizzicato.ogg:system/media/audio/notifications/pizzicato.ogg \
    $(LOCAL_PATH)/notifications/ogg/Plastic_Pipe.ogg:system/media/audio/notifications/Plastic_Pipe.ogg \
    $(LOCAL_PATH)/notifications/ogg/Polaris.ogg:system/media/audio/notifications/Polaris.ogg \
    $(LOCAL_PATH)/notifications/ogg/Pollux.ogg:system/media/audio/notifications/Pollux.ogg \
    $(LOCAL_PATH)/notifications/ogg/Pong.ogg:system/media/audio/notifications/Pong.ogg \
    $(LOCAL_PATH)/notifications/ogg/Procyon.ogg:system/media/audio/notifications/Procyon.ogg \
    $(LOCAL_PATH)/notifications/ogg/Proxima.ogg:system/media/audio/notifications/Proxima.ogg \
    $(LOCAL_PATH)/notifications/ogg/Radon.ogg:system/media/audio/notifications/Radon.ogg \
    $(LOCAL_PATH)/notifications/ogg/Rang.ogg:system/media/audio/notifications/Rang.ogg \
    $(LOCAL_PATH)/notifications/ogg/Regulus.ogg:system/media/audio/notifications/Regulus.ogg \
    $(LOCAL_PATH)/notifications/ogg/Rubidium.ogg:system/media/audio/notifications/Rubidium.ogg \
    $(LOCAL_PATH)/notifications/ogg/Selenium.ogg:system/media/audio/notifications/Selenium.ogg \
    $(LOCAL_PATH)/notifications/ogg/Shaula.ogg:system/media/audio/notifications/Shaula.ogg \
    $(LOCAL_PATH)/notifications/ogg/Sirius.ogg:system/media/audio/notifications/Sirius.ogg \
    $(LOCAL_PATH)/notifications/ogg/Sirrah.ogg:system/media/audio/notifications/Sirrah.ogg \
    $(LOCAL_PATH)/notifications/ogg/SMS_BellNotice2.ogg:system/media/audio/notifications/SMS_BellNotice2.ogg \
    $(LOCAL_PATH)/notifications/ogg/SMS_BellNotice.ogg:system/media/audio/notifications/SMS_BellNotice.ogg \
    $(LOCAL_PATH)/notifications/ogg/SMS_BrightSMS.ogg:system/media/audio/notifications/SMS_BrightSMS.ogg \
    $(LOCAL_PATH)/notifications/ogg/SMS_Dingdong.ogg:system/media/audio/notifications/SMS_Dingdong.ogg \
    $(LOCAL_PATH)/notifications/ogg/SMS_WarmPiano.ogg:system/media/audio/notifications/SMS_WarmPiano.ogg \
    $(LOCAL_PATH)/notifications/ogg/SpaceSeed.ogg:system/media/audio/notifications/SpaceSeed.ogg \
    $(LOCAL_PATH)/notifications/ogg/Spica.ogg:system/media/audio/notifications/Spica.ogg \
    $(LOCAL_PATH)/notifications/ogg/Stone.ogg:system/media/audio/notifications/Stone.ogg \
    $(LOCAL_PATH)/notifications/ogg/Strontium.ogg:system/media/audio/notifications/Strontium.ogg \
    $(LOCAL_PATH)/notifications/ogg/Syrma.ogg:system/media/audio/notifications/Syrma.ogg \
    $(LOCAL_PATH)/notifications/ogg/TaDa.ogg:system/media/audio/notifications/TaDa.ogg \
    $(LOCAL_PATH)/notifications/ogg/Talitha.ogg:system/media/audio/notifications/Talitha.ogg \
    $(LOCAL_PATH)/notifications/ogg/Tejat.ogg:system/media/audio/notifications/Tejat.ogg \
    $(LOCAL_PATH)/notifications/ogg/Thallium.ogg:system/media/audio/notifications/Thallium.ogg \
    $(LOCAL_PATH)/notifications/ogg/Tinkerbell.ogg:system/media/audio/notifications/Tinkerbell.ogg \
    $(LOCAL_PATH)/notifications/ogg/tweeters.ogg:system/media/audio/notifications/tweeters.ogg \
    $(LOCAL_PATH)/notifications/ogg/Twinkle.ogg:system/media/audio/notifications/Twinkle.ogg \
    $(LOCAL_PATH)/notifications/ogg/Upsilon.ogg:system/media/audio/notifications/Upsilon.ogg \
    $(LOCAL_PATH)/notifications/ogg/Vega.ogg:system/media/audio/notifications/Vega.ogg \
    $(LOCAL_PATH)/notifications/ogg/Voila.ogg:system/media/audio/notifications/Voila.ogg \
    $(LOCAL_PATH)/notifications/ogg/Xenon.ogg:system/media/audio/notifications/Xenon.ogg \
    $(LOCAL_PATH)/notifications/ogg/Zirconium.ogg:system/media/audio/notifications/Zirconium.ogg

# Ringtones
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/ringtones/ogg/Acheron.ogg:system/media/audio/ringtones/Acheron.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Andromeda.ogg:system/media/audio/ringtones/Andromeda.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Aquila.ogg:system/media/audio/ringtones/Aquila.ogg \
    $(LOCAL_PATH)/ringtones/ogg/ArgoNavis.ogg:system/media/audio/ringtones/ArgoNavis.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Atria.ogg:system/media/audio/ringtones/Atria.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Backroad.ogg:system/media/audio/ringtones/Backroad.ogg \
    $(LOCAL_PATH)/ringtones/ogg/BeatPlucker.ogg:system/media/audio/ringtones/BeatPlucker.ogg \
    $(LOCAL_PATH)/ringtones/ogg/BentleyDubs.ogg:system/media/audio/ringtones/BentleyDubs.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Big_Easy.ogg:system/media/audio/ringtones/Big_Easy.ogg \
    $(LOCAL_PATH)/ringtones/ogg/BirdLoop.ogg:system/media/audio/ringtones/BirdLoop.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Bollywood.ogg:system/media/audio/ringtones/Bollywood.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Bongo.ogg:system/media/audio/ringtones/Bongo.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Bootes.ogg:system/media/audio/ringtones/Bootes.ogg \
    $(LOCAL_PATH)/ringtones/ogg/BOOTES.ogg:system/media/audio/ringtones/BOOTES.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Boxbeat.ogg:system/media/audio/ringtones/Boxbeat.ogg \
    $(LOCAL_PATH)/ringtones/ogg/BussaMove.ogg:system/media/audio/ringtones/BussaMove.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Cairo.ogg:system/media/audio/ringtones/Cairo.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Calypso_Steel.ogg:system/media/audio/ringtones/Calypso_Steel.ogg \
    $(LOCAL_PATH)/ringtones/ogg/CanisMajor.ogg:system/media/audio/ringtones/CanisMajor.ogg \
    $(LOCAL_PATH)/ringtones/ogg/CaribbeanIce.ogg:system/media/audio/ringtones/CaribbeanIce.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Carina.ogg:system/media/audio/ringtones/Carina.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Cassiopeia.ogg:system/media/audio/ringtones/Cassiopeia.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Centaurus.ogg:system/media/audio/ringtones/Centaurus.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Champagne_Edition.ogg:system/media/audio/ringtones/Champagne_Edition.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Club_Cubano.ogg:system/media/audio/ringtones/Club_Cubano.ogg \
    $(LOCAL_PATH)/ringtones/ogg/CrayonRock.ogg:system/media/audio/ringtones/CrayonRock.ogg \
    $(LOCAL_PATH)/ringtones/ogg/CrazyDream.ogg:system/media/audio/ringtones/CrazyDream.ogg \
    $(LOCAL_PATH)/ringtones/ogg/CurveBall.ogg:system/media/audio/ringtones/CurveBall.ogg \
    $(LOCAL_PATH)/ringtones/ogg/CyanTone.ogg:system/media/audio/ringtones/CyanTone.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Cygnus.ogg:system/media/audio/ringtones/Cygnus.ogg \
    $(LOCAL_PATH)/ringtones/ogg/DancinFool.ogg:system/media/audio/ringtones/DancinFool.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Ding.ogg:system/media/audio/ringtones/Ding.ogg \
    $(LOCAL_PATH)/ringtones/ogg/DonMessWivIt.ogg:system/media/audio/ringtones/DonMessWivIt.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Draco.ogg:system/media/audio/ringtones/Draco.ogg \
    $(LOCAL_PATH)/ringtones/ogg/DreamTheme.ogg:system/media/audio/ringtones/DreamTheme.ogg \
    $(LOCAL_PATH)/ringtones/ogg/DroidIncomingCall.ogg:system/media/audio/ringtones/DroidIncomingCall.ogg \
    $(LOCAL_PATH)/ringtones/ogg/DroidInvasion.ogg:system/media/audio/ringtones/DroidInvasion.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Droid.ogg:system/media/audio/ringtones/Droid.ogg \
    $(LOCAL_PATH)/ringtones/ogg/DroidRollin.ogg:system/media/audio/ringtones/DroidRollin.ogg \
    $(LOCAL_PATH)/ringtones/ogg/DroidSpeaks.ogg:system/media/audio/ringtones/DroidSpeaks.ogg \
    $(LOCAL_PATH)/ringtones/ogg/DroidTestLab.ogg:system/media/audio/ringtones/DroidTestLab.ogg \
    $(LOCAL_PATH)/ringtones/ogg/DroidX.ogg:system/media/audio/ringtones/DroidX.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Eastern_Sky.ogg:system/media/audio/ringtones/Eastern_Sky.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Enter_the_Nexus.ogg:system/media/audio/ringtones/Enter_the_Nexus.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Eridani.ogg:system/media/audio/ringtones/Eridani.ogg \
    $(LOCAL_PATH)/ringtones/ogg/EtherShake.ogg:system/media/audio/ringtones/EtherShake.ogg \
    $(LOCAL_PATH)/ringtones/ogg/FreeFlight.ogg:system/media/audio/ringtones/FreeFlight.ogg \
    $(LOCAL_PATH)/ringtones/ogg/FriendlyGhost.ogg:system/media/audio/ringtones/FriendlyGhost.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Funk_Yall.ogg:system/media/audio/ringtones/Funk_Yall.ogg \
    $(LOCAL_PATH)/ringtones/ogg/GameOverGuitar.ogg:system/media/audio/ringtones/GameOverGuitar.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Gigolo.ogg:system/media/audio/ringtones/Gigolo.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Gimme_Mo_Town.ogg:system/media/audio/ringtones/Gimme_Mo_Town.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Girtab.ogg:system/media/audio/ringtones/Girtab.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Glacial_Groove.ogg:system/media/audio/ringtones/Glacial_Groove.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Growl.ogg:system/media/audio/ringtones/Growl.ogg \
    $(LOCAL_PATH)/ringtones/ogg/HalfwayHome.ogg:system/media/audio/ringtones/HalfwayHome.ogg \
    $(LOCAL_PATH)/ringtones/ogg/House_of_house.ogg:system/media/audio/ringtones/House_of_house.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Hydra.ogg:system/media/audio/ringtones/Hydra.ogg \
    $(LOCAL_PATH)/ringtones/ogg/InsertCoin.ogg:system/media/audio/ringtones/InsertCoin.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Iridium.ogg:system/media/audio/ringtones/Iridium.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Kuma.ogg:system/media/audio/ringtones/Kuma.ogg \
    $(LOCAL_PATH)/ringtones/ogg/LoopyLounge.ogg:system/media/audio/ringtones/LoopyLounge.ogg \
    $(LOCAL_PATH)/ringtones/ogg/LoveFlute.ogg:system/media/audio/ringtones/LoveFlute.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Lyra.ogg:system/media/audio/ringtones/Lyra.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Machina.ogg:system/media/audio/ringtones/Machina.ogg \
    $(LOCAL_PATH)/ringtones/ogg/MidEvilJaunt.ogg:system/media/audio/ringtones/MidEvilJaunt.ogg \
    $(LOCAL_PATH)/ringtones/ogg/MildlyAlarming.ogg:system/media/audio/ringtones/MildlyAlarming.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Nairobi.ogg:system/media/audio/ringtones/Nairobi.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Nasqueron.ogg:system/media/audio/ringtones/Nasqueron.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Nassau.ogg:system/media/audio/ringtones/Nassau.ogg \
    $(LOCAL_PATH)/ringtones/ogg/NewPlayer.ogg:system/media/audio/ringtones/NewPlayer.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Noises1.ogg:system/media/audio/ringtones/Noises1.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Noises2.ogg:system/media/audio/ringtones/Noises2.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Noises3.ogg:system/media/audio/ringtones/Noises3.ogg \
    $(LOCAL_PATH)/ringtones/ogg/No_Limits.ogg:system/media/audio/ringtones/No_Limits.ogg \
    $(LOCAL_PATH)/ringtones/ogg/OrganDub.ogg:system/media/audio/ringtones/OrganDub.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Orion.ogg:system/media/audio/ringtones/Orion.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Paradise_Island.ogg:system/media/audio/ringtones/Paradise_Island.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Pegasus.ogg:system/media/audio/ringtones/Pegasus.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Perseus.ogg:system/media/audio/ringtones/Perseus.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Playa.ogg:system/media/audio/ringtones/Playa.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Pyxis.ogg:system/media/audio/ringtones/Pyxis.ogg \
    $(LOCAL_PATH)/ringtones/ogg/RadiationOrchestration.ogg:system/media/audio/ringtones/RadiationOrchestration.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Rasalas.ogg:system/media/audio/ringtones/Rasalas.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Revelation.ogg:system/media/audio/ringtones/Revelation.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Rigel.ogg:system/media/audio/ringtones/Rigel.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Ring_Classic_02.ogg:system/media/audio/ringtones/Ring_Classic_02.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Ring_Digital_02.ogg:system/media/audio/ringtones/Ring_Digital_02.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Ring_Synth_02.ogg:system/media/audio/ringtones/Ring_Synth_02.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Ring_Synth_04.ogg:system/media/audio/ringtones/Ring_Synth_04.ogg \
    $(LOCAL_PATH)/ringtones/ogg/Road_Trip.ogg:system/media/audio/ringtones/Road_Trip.ogg \
    $(LOCAL_PATH)/ringtones/ogg/RobotsforEveryone.ogg:system/media/audio/ringtones/RobotsforEveryone.ogg \
