LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),m470)


include $(CLEAR_VARS)
LOCAL_MODULE := libbt-vendor
LOCAL_SRC_FILES := libbt-vendor.so
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/lib
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_OWNER := broadcom
include $(BUILD_PREBUILT)

endif
